package learn.office.excel.bean;

public class SysGridField {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sys_grid_field.id
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sys_grid_field.grid_id
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    private Integer gridId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sys_grid_field.field_name
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    private String fieldName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sys_grid_field.field_alias
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    private String fieldAlias;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sys_grid_field.field_width
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    private Integer fieldWidth;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sys_grid_field.field_state
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    private Integer fieldState;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sys_grid_field.id
     *
     * @return the value of sys_grid_field.id
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sys_grid_field.id
     *
     * @param id the value for sys_grid_field.id
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sys_grid_field.grid_id
     *
     * @return the value of sys_grid_field.grid_id
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    public Integer getGridId() {
        return gridId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sys_grid_field.grid_id
     *
     * @param gridId the value for sys_grid_field.grid_id
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    public void setGridId(Integer gridId) {
        this.gridId = gridId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sys_grid_field.field_name
     *
     * @return the value of sys_grid_field.field_name
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sys_grid_field.field_name
     *
     * @param fieldName the value for sys_grid_field.field_name
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sys_grid_field.field_alias
     *
     * @return the value of sys_grid_field.field_alias
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    public String getFieldAlias() {
        return fieldAlias;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sys_grid_field.field_alias
     *
     * @param fieldAlias the value for sys_grid_field.field_alias
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    public void setFieldAlias(String fieldAlias) {
        this.fieldAlias = fieldAlias;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sys_grid_field.field_width
     *
     * @return the value of sys_grid_field.field_width
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    public Integer getFieldWidth() {
        return fieldWidth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sys_grid_field.field_width
     *
     * @param fieldWidth the value for sys_grid_field.field_width
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    public void setFieldWidth(Integer fieldWidth) {
        this.fieldWidth = fieldWidth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sys_grid_field.field_state
     *
     * @return the value of sys_grid_field.field_state
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    public Integer getFieldState() {
        return fieldState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sys_grid_field.field_state
     *
     * @param fieldState the value for sys_grid_field.field_state
     *
     * @ibatorgenerated Wed Feb 15 10:26:38 CST 2017
     */
    public void setFieldState(Integer fieldState) {
        this.fieldState = fieldState;
    }
}